### ISSUE TITLE
Unable to set env vars per job

### ISSUE THREAD

**Issue by nnashok** [doctormo/python-crontab#1]
I want to set env vars to specific values for my jobs, something like:
```
CRON_TZ="America/Los_Angeles"
* 15 * * * echo "LA: $(date)"

CRON_TZ="America/New_York"
*/2 18 * * * echo "NY: $(date)"
```

However, the package ends up retaining only the last value of the env var and persisting that in the crontab, effectively removing the customization for the jobs. The following example code illustrates the issue:
```python
from crontab import CronTab
import sys

cron = CronTab(tabfile='output.tab')

cron.env['CRON_TZ'] = 'America/New_York'
job  = cron.new(command='/usr/bin/echo "new york"')
job.setall(1, 12, None, None, None)

cron.env['CRON_TZ'] = 'America/Los_Angeles'
job  = cron.new(command='/usr/bin/echo "los angeles"')
job.setall(1, 23, None, None, None)
cron.write( 'output.tab' )
```
The output is:
```
CRON_TZ=America/Los_Angeles
1 12 * * * /usr/bin/echo "new york"
1 23 * * * /usr/bin/echo "los angeles"
```

instead of:
```
CRON_TZ=America/New_York
1 12 * * * /usr/bin/echo "new york"
CRON_TZ=America/Los_Angeles
1 23 * * * /usr/bin/echo "los angeles"
```

**Comment by doctormo** [comment]
That is interesting, it would be nice to have a timezone support built in. But the env does appear to apply to what ever is above it. So that at least needs to be supported with load and save and then we can add an edit api.

What kind of API would you like? `job.timezone = "EST"` or perhaps just a more generic job.env['CRON_TZ'] = "America/New_York"

**Comment by doctormo** [comment]
Additional notes: per crontab timezones are only supported in the Cronie fork of vixie cron, so RedHat, CentOS and maybe later fedora versions. Users of Ubuntu and Debian don't have this feature, other systems may use it depend on what was installed.

**Comment by nnashok** [comment]
Thanks for the quick response. The package should support env vars generally. And the env should be cumulative, i.e any vars set before the job should be effective for the job.

The fact that timezones are supported using the env var should not matter, it was just a use case that I'm working with.

**Comment by doctormo** [comment]
OK, I've worked out a way to handle environment variables per job. I've noted the use cases in the readme and made sure test coverage is still perfect for the new features. Version 2.2.0 is published to pypi.
