### ISSUE TITLE
Line with MAILTO="" in crontab don't work

### ISSUE THREAD

**Issue by Alfred17** [doctormo/python-crontab#11]
If there is a line with MAILTO=""" in the crontab, the "" will be deleted so that the temporary file can no longer be installed and the crontab leave unchanged.

**Comment by doctormo** [comment]
So this would be a environment variable with double quotes, and the quotes are removed because there's no space in the value part.

Can you tell me, what system will it not install into?
What is the error given?
Do you have an example crontab file?

Thanks for the report Alfred!

**Comment by Alfred17** [comment]
I use a Raspi with Rasbian (Debian) Linux. The crontab looks like this:
```
# 
MAILTO=""
# m h  dom mon dow   command
/10 * * * * /home/pi/ClockSync.sh

```
After inserting a new comand with the library the tempfile looks like this:
```
# 
MAILTO=
# m h  dom mon dow   command
/10 * * * * /home/pi/ClockSync.sh
/10 * * * * /home/pi/bla.sh

```
The "" after the MAILTO= are missing and so crontab failes.

**Comment by doctormo** [comment]
Thanks for the extra info, I think I've got the issue tested and fixed.

Can you check python-crontab-2.2.5 and see if this fixes your issue?

**Comment by Alfred17** [comment]
No, the fix doesn't work. If an entry is deleted from the crontab, the MAILTO line is also deleted completely.
When a new entry is written, the MAILTO line is directly in front of the new entry, but without the "". The next call of crontab would fail again.
Here is my test program:

```
#!/usr/bin/python
# -*- coding: utf-8 -*-
import random
import sys
sys.path.append( "/home/pi/crontab" )
from crontab1 import CronTab

#--- Der Cron Job für den AutoUpdate wird erzeugt oder gelöscht ------------------------------
def CronJob( update ):
    AUcomment = "Autoupdate"
    AUcommand = "./AutoUpdate.py"
    CronJobFound = False
    AutoUpdateTagWoche = 1  # Wochentag des Updates
    AutoUpdateStunde   = 12 # Stunde des Updates
    AutoUpdateMinute   = 30 # Minute des Updates

    cron = CronTab(user=True) # Crontab des Users pi
    # Suchen, ob schon ein Job eingetragen ist
    for job in cron:
        print job
    for cron_job in cron.find_comment( AUcomment ):
        CronJobFound = True
        print "Cron Job found"

    if update == 1:
        # Automatische Updates durchführen
        if CronJobFound == False :
            # Der Job ist noch nicht vorhanden -> eintragen
            # Zeit festlegen, zu der nach dem Update gesucht wird und in der "crontab -e" eintragen
            AutoUpdateTagWoche = str(random.randint(0, 6))  # Wochentag des Updates 0-6
            AutoUpdateStunde   = str(random.randint(0, 23)) # Stunde des Updates 0-23
            AutoUpdateMinute   = str(random.randint(0, 59)) # Minute des Updates 0-59
        
            job = cron.new( AUcommand, AUcomment )
            job.setall( AutoUpdateMinute + ' ' + AutoUpdateStunde + ' * * ' + AutoUpdateTagWoche )
            print "Neuer Cron Job", AutoUpdateMinute + ' ' + AutoUpdateStunde + ' * * ' + AutoUpdateTagWoche
            if job.is_valid() == True:
                print "Job is valid"
            cron.write()
    else:
        if CronJobFound == True :
            # Der oder die Jobs müssen gelöscht werden
            cron.remove_all(comment=AUcomment)
            cron.write()
            print "Cron Job gelöscht"

CronJob( 1 )
#CronJob( 0 )

```
Salutations
Alfred

**Comment by doctormo** [comment]
Hi Alfred, the delete issue looks like a separate issue. Probably related to how env is saved against items.

I can't unpick your code to get a working test, can you write a quick test similar to the one I committed in the 2.2.5 release?

**Comment by Alfred17** [comment]
Hi doctormo, 
unfortunately, my Python knowledge is not enough for this. The important thing is that the MAILTO= """line is already in the crontab. How can I run the Unit Test with me? Then I could test whether the problem with the test occurs or not.

**Comment by doctormo** [comment]
The test can be run with:

    python setup.py test

or

    ./setup.py test

Depending on your python.

**Comment by Alfred17** [comment]
Thanks, the test runs without errors. But what's the problem with cutting out my code? Mark in the browser with the mouse, then ^C and insert in an editor with ^V. I use np++.

**Comment by doctormo** [comment]
That means the issue you're having isn't understandable by me. I wasn't able to run your code above using Ubuntu 16.04 python 2.7/3.5

**Comment by Alfred17** [comment]
I reduced the program to what is necessary:

```
from crontab import CronTab

#--- Der Cron Job für den AutoUpdate wird erzeugt oder gelöscht ------------------------------
def CronJob( update ):
    AUcomment = "Autoupdate"
    AUcommand = "./AutoUpdate.py"

    cron = CronTab(user=True) # Crontab des Users pi

    if update == 1:
        # Automatische Updates durchführen
        job = cron.new( AUcommand, AUcomment )
        job.setall( '1 12 * * 3' )
        if job.is_valid() == True:
            print "Job is valid"
        cron.write()
    else:
        cron.remove_all(comment=AUcomment)
        cron.write()
        print "Cron Job deleted"

CronJob( 1 )
#CronJob( 0 )
```
Crontab looks like this:

```
# 
# 
MAILTO=""
#  
/10 * * * * /home/pi/job.py # any job
```
run my program with **python cron.py**

Crontab looks like this:

```
# 
#  
/10 * * * * /home/pi/job.py # any job

MAILTO=
1 12 * * 3 ./AutoUpdate.py # Autoupdate
```
MAILTO is in a different line and the "" are missing.
Repair crontab:

```
# 
MAILTO=""
#  
/10 * * * * /home/pi/job.py # any job

1 12 * * 3 ./AutoUpdate.py # Autoupdate
```
Change my programm to:

```
#CronJob( 1 )
CronJob( 0 )
```
and run it again. crontab looks like this:

```
# 
#  
/10 * * * * /home/pi/job.py # any job
```
The MAILTO line is complete deleted.

**Comment by doctormo** [comment]
Thanks Alfred, I've added your code as tests into the test suite. You can find them in the latest commit. Here using python 2.7 all tests are passing. When I do the update part, the entry is added and MAILTO stays at the top, when I do the remove_all part, the entry is removed and MAILTO continues to be there at the top all with the double quotes.

I'm not sure where to take this since the tests are pretty much what you've written here. Could you take a look at the code and see if I made a mistake in what I've done?

**Comment by Alfred17** [comment]
The test code looks appropriate. I'm running the test without making any mistakes. The main difference I still see is that the test works on a file and not on the user's crontab. Maybe that's what makes the difference?

**Comment by doctormo** [comment]
My local tests show that the existing entry '/10' is wrong, in that it should be */10. I'm looking into why the module allows these values to be output. Can you check to see if this is the issue?

**Comment by Alfred17** [comment]
The test code looks appropriate. I'm running the test without making any mistakes. The main difference I still see is that the test works on a file and not on the user's crontab. Maybe that's what makes the difference?

**Comment by doctormo** [comment]
Did you get caught in a loop? :smiley:

**Comment by Alfred17** [comment]
The test code looks appropriate. I'm running the test without making any mistakes. The main difference I still see is that the test works on a file and not on the user's crontab. Maybe that's what makes the difference?

**Comment by Alfred17** [comment]
Ups, yesterday was a stressful day and it looked as if I hadn't sent the text...

**Comment by doctormo** [comment]
No problem. Sorry to hear you had a stressful day, this year has been crap full of them. I'm going to fix the bug that allows /10 into the output and then see if that fixes the issue, stand by.

**Comment by doctormo** [comment]
OK 2.5.6 should include better error handling and a disabling function so lines that cause errors are disabled.

**Comment by Alfred17** [comment]
I have tested version 2.2.6, no change in behaviour! The "" behind the MAILTO= still disappear!

**Comment by doctormo** [comment]
They don't disappear on Linux Ubuntu 16.04 python 2.7/3.5 on a user crontab. If you discover what the problem is, please reopen this report. But otherwise, there's not a lot I can do to help since the problem can't be reproduced.
