### ISSUE TITLE
CHANGELOG and releases

### ISSUE THREAD

**Issue by MartinThoma** [doctormo/python-crontab#12]
Hi doctormo,

first of all: Thank you for providing the Python module :-) :+1: 

It would be nice if you updated the `CHANGELOG` and used [git tags](https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository). This will "tag" a commit as a release and thus makes it much simpler to compare changes in versions with git tools. So if you use 

```
$ git tag -a v2.2.6
$ git push origin --tags
```

people can see it under the "releases" tab on Github.

See https://github.com/ecederstrand/exchangelib/blob/master/CHANGELOG.rst for a nice example of a changelog

**Comment by doctormo** [comment]
Should be fixed now, I've removed the Changelog, it's an old concept and git log should be used.
