### ISSUE TITLE
Issue with # sign in the script content

### ISSUE THREAD

**Issue by mnawalany** [doctormo/python-crontab#15]
I want to create a crontab with # character inside of command. For example:
```
* * * * * python /tmp/test.py arg_with_\#_character
```
crontab -e works as expected and runs `python /tmp/test.py arg_with_#_character` command every minute, but when I try to do that via library this line is completely ignored.

I think the reason is
```
ITEMREX = re.compile(r'^\s*([^@#\s]+)\s+([^@#\s]+)\s+([^@#\s]+)\s+([^@#\s]+)'
                     r'\s+([^@#\s]+)\s+([^#\n]*)(\s+#\s*([^\n]*)|$)')
SPECREX = re.compile(r'^\s*@(\w+)\s([^#\n]*)(\s+#\s*([^\n]*)|$)')
[...]
self._set_parse(ITEMREX.findall(line))
self._set_parse(SPECREX.findall(line))
```
from crontab.py return empty lists for the given line. Please advise if there is any workaround to escape this # character.

**Comment by doctormo** [comment]
Should now be working, I haven't made a new release yet. But let me know if you need one.
