### ISSUE TITLE
SYSTEMV should be configurable

### ISSUE THREAD

**Issue by abonstu** [doctormo/python-crontab#16]
the embedded linux im using does not support 'special' alias (e.g. @daily) and is not detected as a SYSTEMV operating system.

can the SYSTEMV flag be a configurable option passed to the constructor?

**Comment by doctormo** [comment]
Thanks for the report, I tend to agree that it should be a constructor. Although if you think about it, having the module support both SYSTEMV and not SYSTEMV crons at the same time is a rather niche functionality.

For now you can force SYSTEMV mode by doing `import crontab; crontab.SYSTEMV = True;`

**Comment by doctormo** [comment]
I can also improve the detection support if you can give me information abut the operating system and what comes back from os.uname()

**Comment by doctormo** [comment]
Another ping to see if you can provide data about the system you're on. If not, I'll close the ticket.

**Comment by abonstu** [comment]
Sorry for the lag dude!

```
root@mRDC:~# python
Python 2.7.12 (default, Jan 15 2018, 20:36:31) 
[GCC 4.8.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.uname()
('Linux', 'mRDC', '3.18.84', '#2 Tue Jan 16 08:46:36 AEST 2018', 'mips')
>>> 
```

**Comment by doctormo** [comment]
Do you know what mRDC means?

**Comment by abonstu** [comment]
its the name of the embedded system (product) im working on

**Comment by doctormo** [comment]
I can probably switch to SYSTEMV when we have mips. That should make it fairly useful.
