### ISSUE TITLE
Failed to import CronTab in Docker Container

### ISSUE THREAD

**Issue by phanphuong6** [doctormo/python-crontab#17]
Hi, kindly check this issue. I copy and paste the error message below for your information.

pip install crontab
pip install python-crontab

import crontab
from crontab import CronTab
crontab.SYSTEMV = True

cron = CronTab(user='root')
job = cron.new(
    command='python /dev-tsf/keras-flask/predict_lstm.py',
    user='root')

job.minute.every(1)
cron.write()

When I run the file: python crontab.py

root@79bb69b411b9:/notebooks# python crontab.py
Traceback (most recent call last):
  File "crontab.py", line 11, in <module>
    import crontab
  File "/notebooks/crontab.py", line 12, in <module>
    from crontab import CronTab
ImportError: cannot import name 'CronTab'

Many thanks in advance.

**Comment by doctormo** [comment]
Do NOT install package `crontab` only package `python-crontab`, they are conflicting packages and should not be used together.
