### ISSUE TITLE
implement crontab validation method

### ISSUE THREAD

**Issue by olexandr-klymenko** [doctormo/python-crontab#18]
It is quite obvious for the package to have a way to validate crontab line/item/whatever, i.e.:

```
CRONTAB_TIME_FORMAT_REGEX = re.compile(
    r"^{0}\s+{1}\s+{2}\s+{3}\s+{4}$".format(
        r"(?P<minute>[\d\*]{1,2}([\,\-\/][\d\*]{1,2})*)",
        r"(?P<hour>[\d\*]{1,2}([\,\-\/][\d\*]{1,2})*)",
        r"(?P<day>[\d\*]{1,2}([\,\-\/][\d\*]{1,2})*)",
        r"(?P<month>[\d\*]{1,2}([\,\-\/][\d\*]{1,2})*)",
        r"(?P<day_of_week>[0-6\*]([\,\-\/][0-6\*])*)"
    )
)


def crontab_entry_validator(entry):
    is_crontab = CRONTAB_TIME_FORMAT_REGEX.search(entry)
    if is_crontab is None:
        raise InvalidJobConfiguration(f"Invalid crontab entry: '{entry}'")
    return entry
```

**Comment by doctormo** [comment]
Hi Olexander,

Thanks for the collaboration.

This looks like most of a patch and an idea. Is there more information you can tell me about the issue or the feature and if you need it integrating or if you're planning on doing that yourself?

**Comment by guettli** [comment]
Today I had the same idea: Validation.

On a production system I get this warning:

> 2018-05-07 10:47:55 crontab.setall +919: WARNING  [16130] Unknown cron range value "(/tmp/crontab.QhPMjd"

I used this:
{{{
import crontab
crontab.CronTab(user=True)
}}}

It would be nice if I could use the library for validation. And it would be nice if I could see the particular line which is broken.

**Comment by doctormo** [comment]
I believe this can be done already with enumerate plus a loop through the cron items checking is_valid(), you can also make CronSlices and items and check for validation without a crontab.
