### ISSUE TITLE
ImportError: cannot import name CronTab

### ISSUE THREAD

**Issue by tng10** [doctormo/python-crontab#19]
Hey folks,

I've got this error: `ImportError: cannot import name CronTab` after running this `from crontab import CronTab`

I **do not** have crontab package installed! 
I installed using ```pip install python-crontab``` (version 2.2.8)

**Comment by doctormo** [comment]
Run this code:

```
import crontab
print("{m.__pkgname__} from {m.__file__}".format(m=crontab))
```

You should get something like: `python-crontab from /tmp/bash-venv/15006/local/lib/python2.7/site-packages/crontab.pyc` or similar. If it says ` from crontab.py` then you've got a local file called `crontab.py` which is getting namespace confused with the global module.

**Comment by tng10** [comment]
Ohh... I see
In fact I had a file `crontab.pyc` that I created before installing this package. It was using this reference instead of yours.
Thank you for your quick response!
