### ISSUE TITLE
env vars are not inherited from the previous set value

### ISSUE THREAD

**Issue by nnashok** [doctormo/python-crontab#2]
If I have:
```
MYNAME='Random'
* * * * * echo "$MYNAME"
* * * * * echo "$MYNAME again"
```

then env var `MYNAME` is attached only to the first job and not to the second. The second job should inherit all env that have been reset before its declaration.

Output seen using code:
```python
for job in cron:
    print(job)
    print('job.env: ' + str(job.env))
 ```

```
MYNAME='Random'
* * * * * echo "MYNAME"
job.env: MYNAME='Random'

* * * * * echo "MYNAME"
job.env: 
```

Expected output:
```
MYNAME='Random'
* * * * * echo "MYNAME"
job.env: MYNAME='Random'

MYNAME='Random'
* * * * * echo "MYNAME"
job.env: MYNAME='Random'
```

**Comment by doctormo** [comment]
This is actually the correct behaviour. str(...) will only output variables that are different, this is because this is the output that will go into the crontab.

If you do:

```
print job[0].env['MYNAME']
print job[1].env['MYNAME']
```

You'll see that the dictionary has access to both variables.

**Comment by doctormo** [comment]
I'm going to close this issue if thats ok. Let me know if you're ok with the way the API works.

**Comment by nnashok** [comment]
Thanks for the clarification, it works as you described above.
