### ISSUE TITLE
Information on using this tool with Docker.

### ISSUE THREAD

**Issue by nanomosfet** [doctormo/python-crontab#20]
Has anyone tried using this library in a docker container?

Some questions that come to mind are:
What user do you use with creating the instance `CronTab(user='username')`?
If you have replicas that are running then how can you ensure that each container is coordinating the cron jobs with the other containers? i.e. You have 2 replicas containers in your stack that use this tool, when it runs on both containers will the cron job be done twice.

**Comment by doctormo** [comment]
I'm not sure. I have no experience with docker or it's crontab support. I suspect that it's going to be the normal rules for docker crontabs (if they have them). If you're talking about the internal scheduler daemon, then that'll run a loop that'll run the processes for every time the daemon is running. It's really stupid.

**Comment by nanomosfet** [comment]
Thanks! Ended up going with a different approach. Closing this!
