### ISSUE TITLE
anacron compatibility

### ISSUE THREAD

**Issue by mrfunkyjunkie** [doctormo/python-crontab#21]
based on the supplied doco @ https://pypi.python.org/pypi/python-crontab

this module supports the use of aliases for 'daily/weekly/monthy/reboot' etc - however, when testing this on oracle EL 7.4 (setting up all jobs as root) - I find it will not accept the jobs generated using this module / this syntax, as it does not provide the required 'delay' and 'descriptor' fields required for anacron compatibility.

can provide examples/steps to reproduce as required.

**Comment by doctormo** [comment]
STR will not be useful as I don't have access to oracle EL. Examples would be great though.

**Comment by mrfunkyjunkie** [comment]
Hi @doctormo 

- oracle EL7.4 - can be obtained by registering on the oracle site then adding the ISO to the cart & progressing through to their 'download manager'.

below is a good subset of information further explaining the issue / with examples / references - and I can happy provide more insight upon request.

`#/tmp/test.sh - just outputs 'current time' - which is redirected to a file - when cron executes it - there should be a related an entry in the /var/log/cron log
# - crontab doesnt return any obvious errors with the syntax (when manually loading /var/spool/cron & manual exports of crontab using 'crontab -l > crontab.file' - however 'anacron' seems to return errors due to it lacking the 'delay' and 'description' fields.
# - also - anacron only seems to support 'running as root'.

#reference crontab (generated by hand - working syntax): 
#interval, delay, description, cmd 
@daily 1 testymctestface /tmp/test.sh > /tmp/tst.txt
@daily 3 dummymcdummyface /tmp/test.sh > /tmp/tst.txt

#reference crontab (generated by python-crontab using below function - subsequent other functions are responsible for performing 'cron.write()' & finalization of the crontab)
#interval, cmd - broken syntax

@hourly /tmp/datetime.sh > /tmp/datetime-every-hour1.txt
@hourly /tmp/datetime.sh > /tmp/datetime-every-hour2.txt

[root@testbox tmp]# /usr/sbin/anacron -t /var/spool/cron/root -d
Anacron started on 2018-01-24
anacron: Invalid syntax in /var/spool/cron/root on line 3 - skipping this line
anacron: Invalid syntax in /var/spool/cron/root on line 4 - skipping this line
anacron: Invalid syntax in /var/spool/cron/root on line 15 - skipping this line

[root@testbox anacron]# /usr/sbin/anacron -f -S /var/spool/cron/ -n -d
Anacron started on 2018-01-22
Will run job `cron.daily'
Will run job `cron.weekly'
Will run job `cron.monthly'
Jobs will be executed sequentially
Job `cron.daily' started
Job `cron.daily' terminated
Job `cron.weekly' started
Job `cron.weekly' terminated
Job `cron.monthly' started
Job `cron.monthly' terminated
Normal exit (3 jobs run)

++++++++++++++++++++

def set_interval(cron_job, interval):


    if interval == 'daily':
        cron_job.every().dows()
    if interval == 'weekly':
        cron_job.hour.on(7)
        cron_job.dow.on('MON')
    if interval == 'hourly':
        cron_job.hour.every(1)

`

**Comment by doctormo** [comment]
Ah I think I understand what's happening here. This isn't an OEL thing, it's an anacron thing.

So the only support we currently have for anacron, is lightly parsing it to find out when jobs are going to run. We don't support reading anacron files in the main library currently.

Although it's an interesting feature to have.
