### ISSUE TITLE
Cron Remove Not Working

### ISSUE THREAD

**Issue by DovahBrownies** [doctormo/python-crontab#25]
I can't seem to remove existing con jobs using the command `cron.remove`.
Sample code:
```
from crontab import CronTab
from datetime import datetime

cron = CronTab(user=True)

NewJob = cron.new(command='ls', comment='JobID1')
NewJob.setall(datetime(2018,4,2,10,2))
cron.write()

from job in cron:
     print job

# Tried all of the following:
cron.remove( NewJob)
cron.remove_all(comment='JobID1')
cron.remove_all(command='ls')
```

I even tried running the remove commands in a separate file (not in the same file as `cron.write()`) but to no avail. The code runs without errors but nothing happens.

**Currently running this on Raspberry Pi 3 with Python 2.7.9.**

**Comment by doctormo** [comment]
Are you doing another cron.write() after your remove commands?

**Comment by DovahBrownies** [comment]
I am not. The full code is displayed up there ^^.
I'm writing, then removing.

**Comment by doctormo** [comment]
If you don't write out the removal, you won't be removing anything.

**Comment by DovahBrownies** [comment]
Ah I see. Thank you! I didn't really think of it that way, but I guess that does make sense.
