### ISSUE TITLE
error de privilegios

### ISSUE THREAD

**Issue by guillermoj09** [doctormo/python-crontab#26]
I'm occupying wsgi

def programarCtrPres(self, *arg):
#22 
        
        cron = CronTab(user='guillermo')
        job = cron.new(command='python /home/guillermo/sidomci/script.py')
        job.setall(datetime(2018,04,21,18,50))
        cron.write()
Error !
Read crontab guillermo: must be privileged to use -u

**Comment by guillermoj09** [comment]
ayudame ? es el unico lugar que me puede ayudar

**Comment by doctormo** [comment]
No te puedo ayundar en español.

The error you have is saying that you can't edit the crontab of a user on the system that you are not without admin access (i.e. root) if you set user=True, then you will edit the user you are currently logged in as.

**Comment by guillermoj09** [comment]
hello, I worked with crontab using a static file and executed it from the terminal, but I want to implement it in a web application using apache and the WSGI module, when implementing it the job is done but it is not written in the crontab file (use crontab -l to verify)
I think the problem lies in the cron.write () but I do not know how to fix it
I am implementing a domotic system

def programarCtrPres(self, *arg):
      cron = CronTab(user=True)
        job = cron.new(command='python /home/guillermo/sidomci/script.py')
        job.minute.every(1)
        cron.write()

**Comment by doctormo** [comment]
It will save the crontab in the user that the process is running. If your `wsgi` module is running as `www-data` or similar then you will have a crontab for user `www-data` and not user `guillermo`

Can you confirm this fails when you run it manually from a terminal as your user?

**Comment by guillermoj09** [comment]
it does not fail when I run it from a terminal

if you take that user by default www-data I just checked it by the command pwd.getpwuid (os.getuid ())
but I want to save the crontab in the user that I want

**Comment by doctormo** [comment]
It is the operating system which is saying NO. The library can not help Apache break the security of your computer. You must a) run a process as root which does the saving, you can do this via a different cron, b) run a process as the target user which eats a cron file and saves it to itself.

this is not a normal way of doing things of course. Poking holes in your security should be thought about very seriously.

I'm going to close this issue as an issue, but we can continue to talk here.

**Comment by guillermoj09** [comment]
thanks, I know that this has nothing to do with the specific topic, but I want to occupy the crontab of the www-data user which when I create it does not do anything like execute a script.py

**Comment by doctormo** [comment]
That might be a system property, something stopping the cron tab for non 1000+ users. But that sounds like an operating system thing. I've never heard of such a restriction though. If you find out,let me know!
