### ISSUE TITLE
Fails to parse  */59 * * * * pattern - version 2.2.8

### ISSUE THREAD

**Issue by pavanvamsi3** [doctormo/python-crontab#28]
Similar to https://github.com/doctormo/python-crontab/issues/22

Cron file:
```
# monitorCron
*/59 * * * * python /www/example_app/testing_cron.py
```

Code:
```python
from crontab import CronTab

cron_obj = CronTab(tabfile='crons')
print cron_obj
```
Output/Error:
```
No handlers could be found for logger "crontab"
# monitorCron
# DISABLED LINE
# */59 * * * * python /www/example_app/testing_cron.py
```

**Comment by pavanvamsi3** [comment]
@doctormo Ping.

**Comment by doctormo** [comment]
Thanks for the ping, I'll add this to the tests now and see what comes out.

**Comment by doctormo** [comment]
There seems to be an underlying issue that isn't logged correctly, I've added the basicLogger and some testing to check logging is doing the right thing. But your specific issue can't be reproduced, I'm hoping that with logging fixed, you'll be able to re-run your code and fetch the specific error.

**Comment by doctormo** [comment]
OK I've pushed version 2.3.0 to try and nail down the specific issues. Please try and comment back.

**Comment by pavanvamsi3** [comment]
Thanks, 59 issue seems to be fixed.
