### ISSUE TITLE
remove is not work

### ISSUE THREAD

**Issue by lgjabc** [doctormo/python-crontab#29]
from crontab import CronTab

cron = CronTab(user='scrapyer')

job = cron.new(command='python example1.py')  
job.minute.every(1)

cron.write()  
print "Job created"

for job in cron:  
    print job

cron.remove(job)  
print "Job removed"

cron = CronTab(user='scrapyer')
for job in cron:  
    print job

“”“”“
scrapyer@04:~/ccss/wx$ python mycrontab.py 
Job created
'* * * * * python example1.py'
Job removed
'* * * * * python example1.py'
“”“”“
all the remove func are unavailable，Does not really remove the contents of the /var/spool/cron/crontabs/scrapyer ，Is the method I used wrong?

**Comment by doctormo** [comment]
It looks like you didn't write out before you opened it up again. You must write out once you've removed (or done any action) for it to take effect.

**Comment by lgjabc** [comment]
cannot modify the crontab tasks that have been written to the file(/var/spool/cron/crontabs/scrapyer )?
