### ISSUE TITLE
All lines are marked as "# DISABLED LINE"

### ISSUE THREAD

**Issue by RichardRo** [doctormo/python-crontab#31]
Hi, 
I tried to add crontab lines by:
    cron.lines = lines 
    cron.write()
After running above code, the crontab lines are all marked as "# DISABLED LINE".

Check the source code, find this:
```
    def render(self, errors=False):
        """Render this crontab as it would be in the crontab.
        errors - Should we not comment out invalid entries and cause errors?
        """
        crons = []
        for line in self.lines:
            if isinstance(line, (unicode, str)):
                if line.strip().startswith('#') or not line.strip():
                    crons.append(line)
                elif not errors:
                    crons.append('# DISABLED LINE\n# ' + line)
                else:
                    raise ValueError("Invalid line: %s" % line)
            elif isinstance(line, CronItem):
                if not line.is_valid() and not errors:
                    line.enabled = False
                    crons.append(unicode(line))
```
Maybe this line:
` if line.strip().startswith('#') or **not** line.strip(): `
should be:
` if line.strip().startswith('#') or line.strip(): `
? 
Thanks.

**Comment by doctormo** [comment]
The proposed change would actually break a lot of things, firstly by appending DISABLED onto every empty line but then also by allowing broken lines to be printed.

Setting the lines directly was never meant to be a possible way of adding cron items. But I've changed the code in crontab 2.3.1 to allow for this possibility and protected it from setting crons.
