### ISSUE TITLE
log littering

### ISSUE THREAD

**Issue by voidpp** [doctormo/python-crontab#32]
https://github.com/doctormo/python-crontab/blob/master/crontab.py#L153
If I import the crontab module, the basicConfig add a new definitely unwanted handler to the logging and duplicate every log messages for me (with a shitty format, but it's irrelevant).

python-crontab version: 2.3.0+

**Comment by eis271828** [comment]
```
#!/usr/local/bin/python2.7

import crontab
import logging

logger = logging.getLogger("myProduct")
handler = logging.FileHandler("/tmp/myProduct.log")
handler.setLevel(logging.DEBUG)
logger.addHandler(handler)
logger.setLevel(logging.DEBUG)
logger.debug("test message")
```

Don't import crontab and you only get messages in myProduct.log. Do import crontab and you get messages on the error stream as well.

**Comment by doctormo** [comment]
This is an interesting error, I just fixed the logging because it was silent for most users, making them confused.

What do you expect the module to do for logging?

**Comment by voidpp** [comment]
> What do you expect the module to do for logging?

I expect to do nothing. Just use the logger. As I see, the log configuration should be done only by the application.

I think it would be really disturbing if every python module did logger config. (and most of them don't do this)
