### ISSUE TITLE
Crash on remove of specific job

### ISSUE THREAD

**Issue by codeblooded** [doctormo/python-crontab#33]
I'm trying to run the `CronTab#remove` method, and it's printing a stack trace.

This is my code:

```
    def unschedule(self):
        """
        Unschedule a cronjob for this instance.
        """
        cron = CronTab(user=True)
        cronjob = cron.find_command(self.get_command())
        cron.remove(cronjob) # it fails here
```

This is what I see (minus proprietary, unrelated code):
```
  File "/home/USER_MASKED/.local/lib/python3.4/site-packages/crontab.py", line 474, in remove
    result += self._remove(item)
  File "/home/USER_MASKED/.local/lib/python3.4/site-packages/crontab.py", line 480, in _remove
    for sibling in self.lines[self.lines.index(item)+1:]:
ValueError: <generator object find_command at 0x7fad20752438> is not in list
```

I'm running Python 3.4.3 and python-crontab version 2.3.0

**Comment by codeblooded** [comment]
I used the same method `self.get_command()` to generate the command, so I know that it's identical to the one that was scheduled. The scheduling is working fine.

**Comment by doctormo** [comment]
You can use `self.remove_all(command=self.get_command())` to shorten your code, but I've also pushed a fix to help stop the given error and allow generators to be used in the remove command.
