### ISSUE TITLE
setall fails to set time with Python 3

### ISSUE THREAD

**Issue by michaalbert** [doctormo/python-crontab#35]
Hi!
I had the follwing issue using `setall()` on Debian 9.4 with Python 3.5:
Instead of setting a time for a task it leaves the task's time field blank.
```
cron = CronTab()
job = cron.new(command=foo')
job_t =  datetime.time(0, 30, 0, 0)
job.setall(job_t)
print(job)
```
Expected output:
```
30 0 * * * foo
```
Actual output:
```
* * * * * foo
```

**Comment by doctormo** [comment]
I've added your specific time test to the test suite, it's passing for both python3 and python2. Can you double check the version your using is the latest one? (and let me know which version you have)

**Comment by michaalbert** [comment]
I just noticed that I was still on version 1.9.3 of python-crontab instead of the newest one. With the newest version it works just fine.  Please excuse the trouble! I'll double-check next time.

**Comment by doctormo** [comment]
Could you bug debian to update their package and point them to this issue? (would be a real help to me)
