### ISSUE TITLE
Deleting the earlier listed job removes shared env vars

### ISSUE THREAD

**Issue by nnashok** [doctormo/python-crontab#7]
If I have a crontab where two jobs share an env var, e.g:
```
  DEBUG=1
  1 * * * * echo 1 # First
  2 * * * * echo 2 # Second
```

deleting the first job deletes the env var completely. The second job above is then left without the env var that it was sharing with the deleted job. Following code illustrates the problem:

```
#!/usr/bin/env python

from crontab import CronTab

cron = CronTab(tab="""
DEBUG=1
1 * * * * echo 1 # First
2 * * * * echo 2 # Second
""")

print('After creating the jobs')
for job in cron:
    print('DEBUG: ', job.env['DEBUG'])

print('Removing the first job')
cron.remove_all(comment="First")

print('After removing the first job')
for job in cron:
    print('DEBUG: ', job.env['DEBUG'])
```

**Comment by nnashok** [comment]
Thanks for the quick fix @doctormo . Has this been released yet? I see 2.2.2 as the latest that was released on 2017-05-04.

**Comment by doctormo** [comment]
No release yet. Could you take a quick look at #8 and see if it's a real issue, I don't think it is, but a second opinion would be invaluable.

**Comment by nnashok** [comment]
I tested the code from github and the fix works as expected. If you can release it, that would be great.

**Comment by doctormo** [comment]
Release 2.2.3 released on pypi
