### ISSUE TITLE
Problem with remove_all

### ISSUE THREAD

**Issue by vernonr3** [doctormo/python-crontab#8]
My tests with remove_all for commands indicate an issue with the documentation. The documentation implies that remove_all(command=cmd) will remove the command from the crontab.
This doesn't fit the code - which insists find_command (crontab.py) that the pattern supplied is a compiled regex. 
It also doesn't mention that you need to issue a Crontab.write to the flush this back to disk...

Don't know whether you simply want to amend the documentation or subsume the regex into the code.

Thanks

**Comment by doctormo** [comment]
remove_all _should_ work by taking either a string, or a compiled regex. So remove_all('firefox') and remove_all(re.compile('\wire[fs]ox')) should both work.

Under section: **How to Use the Module**

> Note: Several users have reported their new crontabs not saving automatically. At this point you MUST use write() if you want your edits to be saved out. See below for full details on the use of the write function.

**Comment by nnashok** [comment]
I found that both worked:
```
cron.remove_all(command="firefox")
cron.remove_all(command=re.compile('\wire[fs]ox'))
```

**Comment by doctormo** [comment]
Thanks for the test!
